runners:
  - name: "aws-amd64-32c"
    cloud: "aws"
    instance_type:
      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"

      - "c5a.8xlarge"
      - "c5ad.8xlarge"
      - "c6a.8xlarge"
      - "c6i.8xlarge"
      - "c6id.8xlarge"
      - "cc2.8xlarge"
    machine_image: 
      - "ami-0229a5e9a150a9446"
    region:
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"
      - "us-east-2"

      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"
      - "us-west-1"

      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"
      - "us-west-2"

      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
      - "en-west-1"
    preemptible: false
    labels:
      - "cirun-aws-amd64-32c"
