name: Lint

on:
    pull_request: {}
    workflow_dispatch: {}
    push:
        branches:
            - main
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    lint:
        runs-on: "cirun-aws-amd64-32c--${{ github.run_id }}"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: test
              run: |
                echo "hello world"

